version: '3'
services:
  db:
    container_name: mysql_local
    image: mysql:9.0.0

    environment:
      MYSQL_DATABASE: 'advertisement'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: Asia/Seoul
    ports:
      - '3306:3306'
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d

